### ISSUE TITLE
Darksky bought by Apple and will shut down soon - alternatives?

### ISSUE THREAD

**Issue by e-alfred** [andrewcourtice/ocula#39]
Hello,

Darksky will shut down soon (end of 2021) [1], so this app will not work anymore correctly. Do you have any alternative for that? OpenWeatherMap seems to be a nice alternative.

[1] https://blog.darksky.net/

**Comment by kerry-tarrant** [comment]
Hi Andrew. I'm really digging Ocula. I just have a couple questions.
1) What do you plan do once Darksky shuts down their API?
2) Are you still accepting patrons on Patreon?
Thanks for the amazing app!

**Comment by andrewcourtice** [comment]
Hi @kerry-tarrant 

Thank you for your kind words - I really appreciate it.

In answer to your questions:

1. Since the announcement of DarkSky's acquisition I have decided to discontinue adding new features to Ocula. I am considering using an alternative weather provider such as OpenWeatherMap (as per @e-alfred 's suggestion) but I am still undecided.
2. Given that I am not actively working on Ocula I have temporarily disabled my Patreon campaign. If/when I start work on Ocula again I will most likely start my campaign again.

Once I make a decision on whether to migrate Ocula over to a different provider I will let you know :)

Thanks again for your kind words and support!

**Comment by andrewcourtice** [comment]
Hi @e-alfred @kerry-tarrant 

I just wanted to give you a quick update on Ocula. 

I have begun development on this project again and have since migrated the API to Open Weather Maps. I am expecting to release the new version in conjunction with the official release of Vue 3 in the coming weeks.

In addition to moving the app to a new architecture and weather provider I have taken this opportunity to refresh the design a bit and add some little tweaks like themes (particularly dark theme) and a better navigation experience.

Here's a very early preview of some of the changes:

![Screenshot_20200816-090414.jpg](https://user-images.githubusercontent.com/11718453/90323080-a8064a00-df9f-11ea-8bb3-5c26d6a64e72.jpg)![Screenshot_20200816-090438.jpg](https://user-images.githubusercontent.com/11718453/90323082-accafe00-df9f-11ea-839c-431f8f89dd1c.jpg)![Screenshot_20200816-090451.jpg](https://user-images.githubusercontent.com/11718453/90323083-b05e8500-df9f-11ea-9a74-1e582cc6f22c.jpg)![Screenshot_20200816-090515.jpg](https://user-images.githubusercontent.com/11718453/90323085-b3f20c00-df9f-11ea-91e7-10348b3fc0bf.jpg)![Screenshot_20200816-090529.jpg](https://user-images.githubusercontent.com/11718453/90323088-b81e2980-df9f-11ea-9b25-0ac2ac356e98.jpg)

Thanks

**Comment by kerry-tarrant** [comment]
@andrewcourtice Thanks for getting back into development. Also, the new skin looks really nice! I'm looking forward to trying out the night mode.

Over the past week, I've showed some friends Ocula, and they really like the clean and simple look of the app.

**Comment by andrewcourtice** [comment]
@kerry-tarrant Thanks for the feedback :)

You're welcome to have a play with the development environment while I'm working on it. If you encounter any problems with it just delete your site history for that domain and it should be good to go after that.

The development environment is available at: https://ocula-git-refactor-owm-migration.andrewcourtice.now.sh/
